### ISSUE TITLE
Add requests logging

### ISSUE THREAD

**Issue by bazko1** [polly3d/mockai#11]
Hi Folks I started using the simulator and it works great, but it would be nice to have some requests / response logging for example using [morgan](https://github.com/expressjs/morgan). 
This would be useful for debugging incorrect endpoint path configuration or unimplemented paths.

Would you be interested in pulling contribution with addition of logging?

**Comment by ctrahey** [comment]
I would love this! I found mockai for a use case in integration testing, so I need some way to confirm that certain calls took place, and one simple way to do this would be to watch logs. Metrics could work too!

**Comment by rastogiji** [comment]
This makes sense. I'm thinking of adding more [observability](https://github.com/polly3d/mockai/issues/13) into the system in general. So metrics and logs are a good use case. Let me work on it
