### ISSUE TITLE
HTTP 413 Payload Too Large when sending image inline

### ISSUE THREAD

**Issue by ctrahey** [polly3d/mockai#14]
I'm using MockAI for a call that includes image inline. The call works toward OpenAI.
I'm not sure what the limit should be, but hopefully this project can simply discard and ignore the input?

` HTTP Request: POST http://mock_third_party:8000/v1/chat/completions "HTTP/1.1 413 Payload Too Large`

Let me know if you need more info about it. By my napkin math, my request should be around 70MB

**Comment by polly3d** [comment]
Thank you for using this repo. I don't have a large dataset to reproduce the bug. However, I found a very simple solution that might help you. If this is a major requirement, I can modify the code accordingly.

[Error: request entity too large](https://stackoverflow.com/questions/19917401/error-request-entity-too-large)

`app.use(express.json({limit: '50mb'}));`

Hope it helps.
